// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package modelsgen

type CoinTransfer struct {
	Sender    string
	Recipient string
	Amount    int64
}

type Merch struct {
	Slug  string
	Price int64
}

type MerchOwnership struct {
	UserName  string
	MerchItem string
	Quantity  int64
}

type User struct {
	Name     string
	Password string
	Coins    int64
}
